### ISSUE TITLE
Generate Share Exception: Unexpected regions of None set for launch after upgrade to 0.63.0

### ISSUE THREAD

**Issue by mckayjuk** [awslabs/aws-service-catalog-puppet#233]
After an Upgrade from v0.32.0 of Puppet to 0.63.0, Puppet now fails to generate a share for a local portfolio share.

**Puppet Log:**
[Container] 2020/01/21 14:23:24 Running command servicecatalog-puppet --info generate-shares manifest-expanded.yaml
INFO MainThread Starting to generate shares for: manifest-expanded.yaml
INFO MainThread looking at REDACTED (multiple lines)
INFO MainThread Looking at enabling-vpc-vending-machine
Traceback (most recent call last):
  File "/usr/local/bin/servicecatalog-puppet", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/cli.py", line 21, in generate_shares
    core.generate_shares(f)
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/core.py", line 75, in generate_shares
    manifest, puppet_account_id, False, tasks_to_run
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/manifest_utils.py", line 466, in convert_manifest_into_task_defs_for_spoke_local_portfolios
    raise Exception(f"Unexpected regions of {regions} set for launch {launch_name}")
Exception: Unexpected regions of None set for launch enabling-vpc-vending-machine
[Container] 2020/01/21 14:23:25 Command did not exit successfully servicecatalog-puppet --info generate-shares manifest-expanded.yaml exit status 1
[Container] 2020/01/21 14:23:25 Phase complete: BUILD State: FAILED

** Puppet Manifest Snippet**
```
accounts:
  ##### Application Account OUs #######
  - ou: ADS/foo
    name: 'ADS-FOO'
    default_region: eu-west-1
    regions_enabled:
      - eu-west-1
    tags:
      - team:ads

  - ou: /JXP/foo
    name: 'JXP-FOO'
    default_region: eu-west-1
    regions_enabled:
      - eu-west-1
    tags:
      - team:jxp

spoke-local-portfolios:
  enabling-vpc-vending-machine:
    portfolio: oss-optional-catalog-factory-product-portfolio
    depends_on:
      - jxp-iam-security-roles
      - ads-iam-security-roles
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/AccountOwner
    deploy_to:
      tags:
        - tag: team:ads
        - tag: team:jxp
          regions: default_region
```
