### ISSUE TITLE
Products being deployed in wrong order despite `depends_on` clause

### ISSUE THREAD

**Issue by sara-h-chen** [awslabs/aws-service-catalog-puppet#234]
## Expected Behavior
SCPuppet would wait for products being referenced in the `depends_on` clause to finish provisioning before attempting to deploy dependencies. 

## Actual Behavior
SCPuppet deploys the products in the wrong order, disregarding the `depends_on` cause.

## Steps to Reproduce the Problem
  1. Build a product, A, with networking products, e.g. VPC, subnets, security groups. Build another product, B, that has a `depends_on` clause on Product A in the Puppet manifest. 

```
  product-a:
    portfolio: example-simple-core-network-portfolio
    product: product-VPC
    version: v1
    parameters:
      ...
    deploy_to:
      accounts:
        - account_id: 'XXX'
          regions: default_region

  product-b:
    portfolio: example-simple-core-network-portfolio
    product: product-TGW
    version: v1
    depends_on:
      - product-a
    parameters:
      ...
    deploy_to:
      accounts:
        - account_id: 'XXX'
          regions: default_region

```
  2. Attempt to deploy the products into a spoke account using Service Catalog Puppet.
  3. Product B fails to deploy, and will be placed in a `ROLLBACK_COMPLETE` status. Running Service Catalog Puppet again, without changing the manifest (simply retrying the failed CodeBuild job in the Service Catalog Puppet pipeline), would result in the product successfully deploying.
  
## Specifications

  - Version: 0.61.2
