### ISSUE TITLE
Exclude Account from OU Expansion

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#36]
It would be useful if I could exclude an account from a launches that targets an OU. E.g. maybe something like the below:

```
accounts:
  - ou: /
    name: 'all-accounts'
    default_region: eu-west-2
    regions_enabled:
      - eu-west-2
    tags:
      - ou:all-accounts

launches:
  product-all-accounts:
    portfolio: portfolio
    product: product
    version: v1
    deploy_to:
      tags:
        - tag: ou:all-accounts
          regions: default_region
          exclude: ['012345678910']
```

Or it could be defined in the `accounts` block.

**Comment by jordan-evans** [comment]
Current workaround for this is to include some logic in the CloudFormation for the Product that will skip resource creation for the particular accounts.

E.g.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SkipDeployAccountId:
    Type: String
    Description: If you set this to an AWS Account ID, resources will not be deployed in the account if the current AWS Account ID matches it.
    Default: ""
Conditions:
  CreateResources: !Not [!Equals [!Ref SkipDeployAccountId, !Ref "AWS::AccountId"]]
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Condition: CreateResources
...
```
