### ISSUE TITLE
Stacks fail to be created with the error: InsufficientCapabilitiesException

### ISSUE THREAD

**Issue by Lazarevsky** [awslabs/aws-service-catalog-puppet#405]
puppet/manifest.yaml:

```
---
accounts:
  -
    default_region: eu-central-1
    regions_enabled:
      - eu-central-1
    name: pseudo-root
    ou: /PseudoRoot
    tags:
      - "type:pseudo-root"
      - "partition:eu"

stacks:
  ccoe-inet-in-controls:
    name: ccoe-inet-in-controls
    deploy_to:
      tags:
        -
          tag: "type:pseudo-root"
          regions: default_region
    version: v1
```

===
- Factory runs successfully and creates the corresponding pipeline for v1 of the stack
- The stack template gets correctly uploaded to the stacks s3 bucket introduced with the latest version of Puppet.
- Version of puppet deployed: 0.110.0

Relevant bits from the Deploy codebuild stage:

<html><body>
<span><span><span>

ERROR: [pid 451] Worker Worker(salt=665065786, workers=**, host=afde8a344890, username=root, pid=387) failed    ProvisionStackTask(manifest_file_path=manifest-expanded.yaml, stack_name=ccoe-inet-in-controls, puppet_account_id=422527312844, region=eu-central-1, account_id=428872220342, bucket=sc-puppet-stacks-repository-422527312844, key=stack/ccoe-inet-in-controls/v1/stack.template.yaml, version_id=, capabilities=[], use_service_role=False, execution=hub)
--

</span></span></span><span><span><span>botocore.errorfactory.InsufficientCapabilitiesException:
 An error occurred (InsufficientCapabilitiesException) when calling the 
CreateStack operation: Requires capabilities : [CAPABILITY_IAM]</span></span></span>
</body>
</html>

It seems that the role the solution is using to create the stack doesn't have IAM Capabilities. I saw a change introduced in 0.110.0 where you introduce a new Stack Service role which does have these permissions, but it is not being used in this case, and I am unsure of how to set that flag to True.

What I mean is this bit:
ProvisionStackTask(manifest_file_path=manifest-expanded.yaml, stack_name=ccoe-inet-in-controls, puppet_account_id=422527312844, region=eu-central-1, account_id=428872220342, bucket=sc-puppet-stacks-repository-422527312844, key=stack/ccoe-inet-in-controls/v1/stack.template.yaml, version_id=, **capabilities=[], use_service_role=False**, execution=hub)
