### ISSUE TITLE
Need a feature to exclude a specific product for selected accounts in launch file

### ISSUE THREAD

**Issue by vasindran** [awslabs/aws-service-catalog-puppet#462]
In few cases, we want a specific product not to be updated by puppet while running or want to disassociate from puppet' s eye. So in this case, we need a feature in launch file to exclusively declare (similar to deploy_to: accounts)that particular product no need to run on those accounts. Like deploy_to: accounts: exclude)

This we are achieving currently by declaring that account based tags in manifest file, if we want to exclude more accounts, then the manifest file get increased with more content of accounts and its specific tags, to avoid this we can directly declare in launch file section of that product easily

**Comment by eamonnfaherty** [comment]
would the following make sense:
``` yaml
launches:
  basic-vpc:
    portfolio: ccoe
    product: basic-vpc
    version: v1
    deploy_to:
      tags:
        - tag: group:spoke
          regions: regions_enabled
          excluding:
            - accounts:
              - 012345678910
  ```
