### ISSUE TITLE
Conditions not working

### ISSUE THREAD

**Issue by koenigmartin** [awslabs/aws-service-catalog-puppet#484]
Hi Eamonn,
we ran into an issue testing conditions (puppet version: 0.154.0):
Following the Kitchen Sink Example we ran into an yaml error during validation and we had to alter the condition definition a bit:

```
conditions:
  IsRBIDev:
    "!Equals":
      - "rbi-dev"
      - "${Custom::env}"
```
The statement passed validation. When referencing the statement from a stack however we got the following error:
![conditions](https://user-images.githubusercontent.com/53942671/156121199-0c7e7070-a221-4cc7-b0e4-3417c5a2b47b.png)

We do get the same error when referencing a single condition as well as referencing multiple, so I dont think this is directly related to the multi org feature but a general issue:

```
stacks:
  ccoe-aws-sct-topic: 
    name: ccoe-aws-sct-topic
    condition: "IsRBIDev"
    ...
```

```
stacks:
  ccoe-aws-sct-sns-topic: 
    name: ccoe-aws-sct-topic
    condition: ["IsRBIDev"]
    ...
```
Best regards, Martin
