### ISSUE TITLE
boto3 parameters that are strings are double quoted

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#487]
the following generates a string which is double quoted:

```
      MYVPC:
        boto3:
          account_id: ${AWS::AccountId}
          arguments:
            ProvisionedProductName: my-vpc
          call: get_provisioned_product_outputs
          client: servicecatalog
          filter: Outputs[?OutputKey==`VpcId`].OutputValue | [0]
          region: ${AWS::Region}
          use_paginator: false
```

generates:
```
"something"
```

But it should generate:
```
something
```
