### ISSUE TITLE
Parametrized Run Subset - Not Working

### ISSUE THREAD

**Issue by mtrampic** [awslabs/aws-service-catalog-puppet#500]
Hi there,
After upgrading from 0.139.0 to 0.162.0, We have faced issue with parametrized runs.

Error is silent and visible only when you have OU with a 100+ AWS accounts as PuppetPipeline run takes lot more than expected as puppet expanded-manifest is not shrink-ed.

# Steps to reproduce
1.  Let's assume you have following manifest:
```yaml
---
accounts:
  - name: pseudo-root
    ou: /PseudoRoot
    default_region: eu-central-1
    regions_enabled:
      - eu-central-1
    tags:
      - "type:pseudo-root"
      - "partition:eu"
  
stacks:
  sct-stack-1:
    name: sct-stack-1
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
    depends_on:
      - name: sct-stack-2
        type: stack
        affinity: stack

  sct-stack-2:
    name: sct-stack-2
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
 
  sct-stack-3:
    name: sct-stack-3
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
 
  sct-stack-4:
    name: sct-stack-4
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
```

2. You try to run following subset:
```yaml
subset:
  name: "sct-stack-1"
  section: "stacks"
  include_dependencies: true
  include_reverse_dependencies: true
```

# Expected results
```yaml
accounts:
  - name: ...
  # Expanded Accounts List
  
stacks:  # Shrink-ed Manifest based on parameters.yaml
  sct-stack-1:
    name: sct-stack-1
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
    depends_on:
      - name: sct-stack-2
        type: stack
        affinity: stack

  sct-stack-2:
    name: sct-stack-2
    active: true
    deploy_to:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
    version: v1
    capabilities:
      - "CAPABILITY_NAMED_IAM"
```

# Actual results 
*Manifest is not shrinked, it includes all features and goes as full blown release.*

I tested 0.164.0, 0.161.0, 0.156.0, 0.153.0 versions issue was same, so some feature change in between 0.139.0 -> 0.153.0 broke the subset'ing of manifest.
