### ISSUE TITLE
Product association reorder not possible

### ISSUE THREAD

**Issue by koenigmartin** [awslabs/aws-service-catalog-puppet#506]
When reordering the roles in the association section of a product the Cloudformation stack cannot update.
We are running puppet version 0.166.1.

Old manifest snipet:
```
  my-product-name:
    portfolio: baseline-optional-portfolio-name
    product_generation_method: import
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/Role3
      - arn:aws:iam::${AWS::AccountId}:role/Role2
      - arn:aws:iam::${AWS::AccountId}:role/Role1
    ...
```

New manifest definition:

```
  my-product-name:
    portfolio: baseline-optional-portfolio-name
    product_generation_method: import
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/Role1
      - arn:aws:iam::${AWS::AccountId}:role/Role2
      - arn:aws:iam::${AWS::AccountId}:role/Role3
    ...
```

The stack created for the association tries to update both associations (A1 and A3). Though as the association still exists it fails.
