### ISSUE TITLE
Using Tag Options with the Service Catalog Tools

### ISSUE THREAD

**Issue by MichaelReubenDev** [awslabs/aws-service-catalog-puppet#527]
Hi there, I work for a company heavily utilising this product to deploy infrastructure in our AWS Organisation. We are currently on a mission to clean up our tagging and making sure that all of our platform resources contain the mandatory tags that we are asking for and relying on for resource discovery in Service Now. I was developing an external method to make this happen that would automate putting the tag share options on any account share after puppet shares the portfolio to the account it's trying to deploy in. However after speaking to Jeff Forest from AWS he informed me that you would be able to work on a native option to support tag options hence creating this issue. 

# Expected results
- Create Tag Options in Factory 
- Tag Options should be shared to all accounts that are being shared from the portfolio 
- Tags should then apply on products in the portfolios 
- Tag Options should also work for the product and portfolio level

If any of this is unclear or I can help with further explanation then reach out to me on:
michael.mellor@rwe.com or feel free to get in contact with Jeff

**Comment by eamonnfaherty** [comment]
0.178.0 was just released and it supports this.  Here are the docs: https://service-catalog-tools-workshop.com/every-day-use/310-using-resource-update-constraints.html

**Comment by MichaelReubenDev** [comment]
That's great thank for the update, we look to update 👍

**Comment by MichaelReubenDev** [comment]
Hi Eamonn I've been looking into implementing this in our test environment today but after thoroughly reading the documentation I'm not sure this does quite what I've asked. As shown in the docs you can use this to preface a resource update constraint on spoke local portfolios as I understand these are the portfolios that you share with your accounts so users of those account's can deploy products from the portfolio that has been shared. However these are not the products that I'm trying to use tag options to update, I want to update the products that we are deploying directly from puppet so that tag options can be set on Factory Portfolios and these tag options will be inherited by the products and underlying resources.

**Comment by nowak-ninja** [comment]
Dear @eamonnfaherty, I would like to add that this is not working for us as we would expect either. I believe the request was to have TagOptions resource created and attached to product or a portfolio in Service Catalog via manifest file. This way, we would be able to spread required tags across resources deployed by SC product and make use of them (in our case protect resources with SCP).

**Comment by eamonnfaherty** [comment]
I caught up with @MichaelReubenDev offline.  The request from @MichaelReubenDev was that the tags associated with portfolios and products cascade to the provisioned resources when they are provisioned using a launch within this solution. 

@nowak-ninja is this what you wanted?

**Comment by nowak-ninja** [comment]
@eamonnfaherty yes, the goal was to have TagOptions resource created and attached to product or portfolio to enforce given tags to be set for provisioned resources during product launch.

**Comment by eamonnfaherty** [comment]
are you using puppet to do the provisioning or will end users be doing it?

**Comment by nowak-ninja** [comment]
I think we use both at R-IT :)

**Comment by MichaelReubenDev** [comment]
There is something already in place for spoke local portfolios so the products that your end users will provision but for our use case we want this to also be enabled for products we provision through puppet itself in launches.

**Comment by nowak-ninja** [comment]
@eamonnfaherty  any chance to tackle the thing?

**Comment by eamonnfaherty** [comment]
I hope to have this out within 2 weeks.

**Comment by sandrich** [comment]
This would be a fantastic feature so +1 and thanks for reopening.

**Comment by pspanwar** [comment]
Hi @eamonnfaherty, Do we have any updates on this feature request ?

**Comment by eamonnfaherty** [comment]
resolved in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.206.0

You can now set 

```yaml
share_tag_options: True
```

Within spoke-local-portfolios and launches:

```yaml
spoke-local-portfolios:
  OptionalProducts:
    product_generation_method: import
    sharing_mode: AWS_ORGANIZATIONS
    share_tag_options: True
    execution: hub-and-spoke-split
    portfolio: OptionalProducts
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/Admin
    deploy_to:
      tags:
        - tag: "role:spoke"
          regions: "default_region"
```

**Comment by eamonnfaherty** [comment]
You can also set it globally using the CLI:
```bash
servicecatalog-puppet set-config-value global_share_tag_options_default True
```
or adding to the config:

```yaml
global_share_tag_options_default: true
global_sharing_mode_default: AWS_ORGANIZATIONS
is_caching_enabled: true
regions:
  - eu-west-1
```
