### ISSUE TITLE
Notification Constraints not supported

### ISSUE THREAD

**Issue by kunzt-aws** [awslabs/aws-service-catalog-puppet#533]
At the moment, the Puppet solution only offers capabilities to include launch constraints for the distributed portfolios.
AWS Service Catalog provides capability to use [notification constraints](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/constraints-notification.html). 

Notification support would enable events from Service Catalog activities, since EventBridge does currently not support events from AWS Service Catalog.

Notification Constraints could be supported in the manifest in the same way as launch constraints are today. Proposed example below:
```
spoke-local-portfolios:
  catalogservicedev-portfolio-distribution:
    portfolio: "users"
    sharing_mode: ACCOUNT
    product_generation_method: import
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/Admin
    constraints:
      launch:
        - product: "CatalogProduct"
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/catalogproduct-launchconstraint-role
      notification:
        - product: "CatalogProduct"
         notificationarns:
            - arn:aws:sns:us-east-1:111111111111:catalog-service-notification-topic
    deploy_to:
      tags:
        - tag: "account:user"
          regions: "default_region"
```
