### ISSUE TITLE
Puppet validation errors un unexpanded manifest

### ISSUE THREAD

**Issue by sandrich** [awslabs/aws-service-catalog-puppet#539]
It seems that the puppet validation does not check against the expanded manifest.
Here some tag definition based on OUs and some single accounts

```
accounts:  
  - ou: /
    name: 'all_accounts'
    default_region: "eu-west-1"
    tags:
      - 'scope:all'
    regions_enabled:
      - us-west-1

    exclude:
      accounts:
        - xxxxx # Management account
      ous:
        - '/Security'


  - account_id: "xxx"
    name: "AWS Management Account"
    append:
      tags:
        - 'role:controltower_management'

  - account_id: "yyy"
    name: "deployment_account"
    append:
      tags:
        - 'role:sct'
```

I expect 'role:sct' to be available during validation. This is the error message I get

```stacks.account-vending-prereqs-puppet-account uses tag role:sct in deploy_to that does not exist```

The expanded version of the manifest does include role:sct though.

Here the expanded one:

```
- account_id: 'xxxx'
  default_region: eu-west-1
  email: ttbc_aws_deployment_prod_mgmt_01@temenos.com
  exclude:
    accounts:
    - yyy
    ous:
    - /Security
  expanded_from: r-mpd5
  name: deployment_prod_mgmt_01
  organization: o-b66927lmx8
  ou_name: /
  regions_enabled:
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  tags:
  - scope:all
  - role:sct
  
  ```
