### ISSUE TITLE
Appending tags does not seem to work on OU

### ISSUE THREAD

**Issue by sandrich** [awslabs/aws-service-catalog-puppet#548]
currently try to append a tag to a specific OU but it seems the sandbox-ou tag is not added after the expanding part

```
accounts:  
  - ou: /
    name: 'all_accounts'
    default_region: "eu-west-1"
    tags:
      - 'scope:all'
    exclude:
      accounts:
        - 128xxxxx0 # Management account
      ous:
        - '/Security'

  - ou: '/Sandbox'
    name: 'sandbox-ou'
    default_region: "eu-west-1"
    append:
      tags:
        - 'sandbox-ou'
```

My expectation is that the account in /Sandbox should have “scope:all” AND “sandbox-ou” applied? But it only has “scope:all”

stack version: 0.185.0
