### ISSUE TITLE
tagging stacks and launches

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#551]
When writing a manifest file I would like to specify tags that get applied to the resources provisioned.  For example:

```yaml
stacks:
  sleeper:
    name: "sleeper"
    version: "v1"
    tags:
      - key: foo
        value: bar
    deploy_to:
      tags:
        - tag: "role:sct"
          regions: "default_region"

```

**Comment by alexeygumirov** [comment]
Will it be possible to assign tags by pulling information from SSM parameter in the target account?

**Comment by eamonnfaherty** [comment]
what would you want to do with that feature?  Are you trying to use a different tag value depending on the account the stack resides in?  what tag is this? I am asking as there could be another way to achieve the same goal but I would need to know a little more about the goal.

**Comment by eamonnfaherty** [comment]
you can now use add 

```yaml
    tags:
      - key: foo
        value: bar
```

to launches and stacks. eg:
```
stacks:
  sleeper:
    name: "sleeper"
    version: "v1"
    tags:
      - key: foo
        value: bar
    deploy_to:
      tags:
        - tag: "role:sct"
          regions: "default_region"
```
