### ISSUE TITLE
constraints.launch.product is not recognised

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#584]
This is valid according to the schema but it fails because of the code:

```
spoke-local-portfolios:
  sharing-is-caring:
    portfolio: aws-resources
    product_generation_method: copy
    sharing_mode: AWS_ORGANIZATIONS
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/Admin
    constraints:
      launch:
        - product: "iron-bucket"
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/human-roles/Operator
    deploy_to:
      tags:
        - tag: "type:test-account"
          regions: default_region
```
