### ISSUE TITLE
Question: Strategy for multi-region with multiple accounts

### ISSUE THREAD

**Issue by peteawood** [awslabs/aws-service-catalog-puppet#667]
- We currently have ~200 accounts all deployed to a single region utilising OU paths in our manifest. 
- We would like to enable other regions. How to do this with Factory and for the launches is clearly documented. 
- However we don't want to enable every account for every region (and therefore deploy products everywhere), only those that need it. 
- An approach for this is also clearly documented (specify the accounts with extra regions separately in the manifest) but it feels like this may become unmaintainable once we hit 15-20 accounts that may all have different required regions. 
- We would also like to automate the process so our Account Vending Machine can select between regions and we can create a Self Service product allowing teams to enable a region for their account.

Is there a strategy documented anywhere which suggests how to approach this situation (a maintainable manifest file that allows enabled_regions per account to be dynamic)?

We have considered

1. Adding accounts separately to the manifest as and when they require additional/alternative regions - Simple but potentially difficult to maintain at scale and to automate.
2. Using a separately deployed product that puppet needs to see in a region before deploying there - Potentially possible with a lambda-invocation depends_on but will result in an out-of-band product deployment and not sure if check would really be account and region specific.
3. Deploying every product to every account in every enabled region regardless of the need. - Manifest stays pretty much the same but we have ~$60 cost per account per month ($12000 monthly for 200 accounts) that could be avoided.
4. Using assertions with an ssm parameter per region per account. Have the root product/launch depend on the assertion so that products are only launched in a region in an account if the assertion is true for that account and region - Similar issues to 2 but feels slightly more native puppet functionality. Again unsure if we would be misusing assertions and also unsure if the affinity of assertion could be scoped to just the one account and region puppet is about to deploy into.
5. Redesigning our manifest to make option 1 work at scale - This would be acceptable but we're not sure what approach would make option 1 more maintainable.
6. Asking on GitHub whether anyone has a better strategy. Hi! 👋

**Comment by eamonnfaherty** [comment]
thanks for reaching out with this request.  I think the current mechanisms for dealing with variance do not cater for this use case without adding an unacceptable level of operational pain. If a new feature was released to make this possible when would you need it for?

**Comment by peteawood** [comment]
Our current target is beginning of August. However it won't need to be immediately scalable, we could use one of the options above (probably option 1 as simplest and supported) for another few weeks past the August target if there was a feature arriving which took care of the operational overhead that we could switch to later.

**Comment by eamonnfaherty** [comment]
As of release https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.233.0 you can now make use of a new construct named external_account_overrides. It allows you to say the default region and or enabled_regions are available from ssm within the home region of the puppet account.

You can specify the following:

```yaml
accounts:
  - ou: "/dev"
    name: "dev-accounts"
    external_account_overrides:
      default_region:
        source: ssm
      enabled_regions:
        source: ssm
    tags:
      - "type:dev"
```

When the puppet manifest is expanded the values will be retrieved from ssm parameter store parameters with the naming convention of: /servicecatalog-puppet/manifest-external-account-overrides/<account_id>/default_region or /servicecatalog-puppet/manifest-external-account-overrides/<account_id>/enabled_regions where <account_id> is the account within the /dev ou.

if you do not wish to provide default_regions or regions_enabled for all accounts you can set fail_if_missing: false on the option:

```yaml
accounts:
  - ou: "/dev"
    name: "dev-accounts"
    external_account_overrides:
      default_region:
        source: ssm
        fail_if_missing: false
      enabled_regions:
        source: ssm
        fail_if_missing: false
    tags:
      - "type:dev"
```

This means the absence of account default regions and regions enabled will be a silent error and may be tricky to spot.  If you are unsure what is happening please check the expanded manifest for the result of the lookups.
