### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace' when using ssm parameters

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#689]
The following config:
```
parameters: 
  VPCId:
    ssm: 
      name: /networking/vpc/VPCId
      account_id: ${AWS::PuppetAccountId}
      path: /networking
```

was causing an exception:

AttributeError: 'int' object has no attribute 'replace' when using ssm parameters
