### ISSUE TITLE
Exclude OU from definition

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#69]
In our current Puppet manifest we have something like this defined to target a launch against all accounts

```yaml
schema: puppet-2019-04-01

accounts:
  - ou: /
    name: 'all-accounts'
    default_region: eu-west-2
    regions_enabled:
      - eu-west-2
    tags:
      - ou:all-accounts

launches:
  my-product-all-accounts:
    portfolio: my-portfolio
    product: my-product
    version: v1
    deploy_to:
      tags:
        - tag: ou:all-accounts
          regions: default_region
```

When we close an AWS Account in our Organisation we clean up all resources inside it, close the account down, then move the account to a `graveyard` OU until the standard 90 days pass (where the account is automatically removed).

The issue we have at the moment is (using the above approach), Puppet still tries to deploy a product to the closed account in the `/graveyard` OU, causing the Puppet run to fail with an `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied` error.

It would be good if we could define something like the below to exclude certain OUs from the target OU:

```yaml
  - ou: /
    name: 'all-accounts'
    default_region: eu-west-2
    regions_enabled:
      - us-east-1
      - eu-west-2
    exclude:
      - /graveyard
      - /path/to/my/ou
    tags:
      - ou:all-accounts
```
