### ISSUE TITLE
Macro get_accounts_for_path doesn't work

### ISSUE THREAD

**Issue by mpratsch** [awslabs/aws-service-catalog-puppet#691]
Hi Eamonn,

I was playing around with the macro but that didn't work.

**Describe the bug**

puppet validation fails (puppet version 0.242.0)

In the manifest.yaml file in puppet I tried the macros described in the documentation. 
```
parameters:
    AllAccountIds:
      macro:
        method: get_accounts_for_path
        args: /
```

Error:

```

yamale.yamale_error.YamaleError: Error validating data with schema '/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/servicecatalog_puppet/schema.yaml'
  parameters.AllAccountIds.default: Required field missing
  parameters.AllAccountIds.ssm: Required field missing
  parameters.AllAccountIds.boto3: Required field missing
  parameters.AllAccountIds.mapping: Required field missing
``` 

I see that's not covered in the schema.yaml.

Do I use it wrong?

Thanks, 
Martina
