### ISSUE TITLE
SSM Override Account Settings Not Working

### ISSUE THREAD

**Issue by SHunnisett** [awslabs/aws-service-catalog-puppet#731]
[SSM Override for Account Settings](https://service-catalog-tools-workshop.com/every-day-use/using-ssm-to-override-account-details.html) is not working as expected

Expected behaviour:  
Puppet uses SSM parameters to retrieve enabled_regions for OU specified in manifest

Current behaviour:
Spoke product fails to deploy due to validation errors (see Testing, below)

Version: 0.246.0

Parameters created in Puppet deployment account:  
/servicecatalog-puppet/manifest-external-account-overrides/<spoke_acct_id>/enabled_regions  
Value: eu-central-1,us-east-2  Type: String

/servicecatalog-puppet/manifest-external-account-overrides/<spoke_acct_id>/default_region  
Value: eu-central-1  Type: String

Intended manifest entry (abridged):  
```
parameters:
  ParamDefaultRegion:
    default: &ParamDefaultRegion "eu-central-1"

accounts:
  - ou: "/OU/OU2"
    name: "OU name"
    default_region: *ParamDefaultRegion
    external_account_overrides:
      enabled_regions:
        fail_if_missing: false
        source: ssm
    tags:
	- tag1:example
```

Testing:
Attempted spoke deployment of product to us-east-2

1. Added override only for enabled_regions - Exception: account entry /OU/OU2 is missing regions_enabled
2. Deleted default_region and added default_region override - Exception: account entry /OU/OU2 is missing default_region
3. Kept override and added regions_enabled but eu-central-1 only - Exception: account entry /OU/OU2 is missing default_region
4. Kept overrides and regions_enabled (only eu-central-1) and added default_region back in.  - Unsupported regions us-east-2 setting for launches: spoke-product-name

Additional Information  
The OU path has been confirmed as identical and case-correct to Organizations
