### ISSUE TITLE
Associations with IAM_PATTERN does not work

### ISSUE THREAD

**Issue by SlashDevNullOps** [awslabs/aws-service-catalog-puppet#732]
Hi Eamonn, greetings from R-IT!

**Describe the bug**
When associating a SC product/portfolio with multiple roles using a wildcard, this leads to an issue. 
The most extreme case is "roles/*" if one wants to make this portfolio available for every role in the account with sufficient iam permissions.

Puppet then tries to match roles and creates an association for each role in the account leading to 100+ dedicated associations of type "IAM Principle" and then fails at some point (for the accounts and roles it did that, that actually works). 

I believe this is the part of the code this is concerning:
https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/workflow/portfolio/associations/create_associations_for_spoke_local_portfolio_task.py#L111

Here the PrincipalType is hardcoded to "IAM". 
According to https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/servicecatalog/client/associate_principal_with_portfolio.html there should be also a value called "IAM_PATTERN". Possibly that should be an optional parameter to switch that.

**To Reproduce**
1. Add an association to a product with a * wildcard in it (eg. Manifest Snippet 1)
2. Run Puppet

**Expected behavior**
A single association of type "Principal Name" is created for "arn:aws:iam:::role/*". This is possible to be done through the console for example. See screenshot in the attachments.

**Attachments**
Manifest Snippet 1:
```
  DnsPrivateZone:
    portfolio: baseline-optional-rcloud-dns
    sharing_mode: AWS_ORGANIZATIONS
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/*
    share_with:
      tags:
        - tag: "type:pseudo-root"
          regions: default_region
```

Example of association done through the console:
![Image](https://github.com/user-attachments/assets/b4644c4d-02e0-46b9-91e1-f3f2f50c2e93)

Thank you and Best Regards!
