### ISSUE TITLE
Apply launch constraint to all products in a portfolio

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#77]
At the moment when we specify Launch Constraints for a Portfolio, we need to do so for each product.

It would be great if there was an easy way to apply the constraint to all products in the portfolio.

```yaml
spoke-local-portfolios:
  account-vending-for-spokes:
    portfolio: demo-central-it-team-portfolio
    depends_on:
      - account-iam-for-spokes
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    constraints:
      launch:
        - product: <all_products>
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    deploy_to:
      tags:
        - tag: scope:spoke
          regions: default_region
```

Don't mind how this is achieved. Maybe getting all products for a portfolio could be a macro, then we could pass the output of the macro into the launch constraint setup?

**Comment by eamonnfaherty** [comment]
Thanks for the report @jordan-evans 

How would you feel about using regular expressions?

```yaml
spoke-local-portfolios:
  account-vending-for-spokes:
    portfolio: demo-central-it-team-portfolio
    depends_on:
      - account-iam-for-spokes
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    constraints:
      launch:
        - product: 
             matching: iam-(.*)
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    deploy_to:
      tags:
        - tag: scope:spoke
          regions: default_region
```

**Comment by eamonnfaherty** [comment]
I think it would be products and not product.  I think it would be a list or a regex:

```yaml
spoke-local-portfolios:
  account-vending-for-spokes:
    portfolio: demo-central-it-team-portfolio
    depends_on:
      - account-iam-for-spokes
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    constraints:
      launch:
        - product: 
             matching: iam-(.*)
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    deploy_to:
      tags:
        - tag: scope:spoke
          regions: default_region
```

or 

```yaml
spoke-local-portfolios:
  account-vending-for-spokes:
    portfolio: demo-central-it-team-portfolio
    depends_on:
      - account-iam-for-spokes
    associations:
      - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    constraints:
      launch:
        - products: 
             - iam-product-1
             - iam-product-2
          roles:
            - arn:aws:iam::${AWS::AccountId}:role/MyServiceCatalogAdminRole
    deploy_to:
      tags:
        - tag: scope:spoke
          regions: default_region
```
