### ISSUE TITLE
Chained Dependencies

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#87]
It would be useful if chained dependencies were respected in the manifest.

For example:
```
launch-A:
    portfolio: portfolio-example
    product: Product1
    version: v1
    deploy_to:
      accounts:
      - account_id: 012345678910
        regions: default_region

  launch-B:
    portfolio: portfolio-example
    product: Product2
    version: v1
    depends_on:
      - launch-A
    deploy_to:
      accounts:
      - account_id: 012345678910
        regions: default_region

  launch-C:
    portfolio: portfolio-example
    product: Product3
    version: v1
    depends_on:
      - launch-B
    deploy_to:
      accounts:
      - account_id: 012345678910
        regions: default_region
```

Would deploy Product1 followed by Product2 followed by Product3
